services:

# Ningnx
web:
  image: nginx:latest
  container_name: nginx-web
  ports:
    - "8080:80"
  volumes:
    - ./html:/usr/share/nginx/html
  networks:
    - app-network
  depends_on:
     - db

# Postgresql Database

db:
  image: postgres:latest
  container_name: postgres-db
  environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
  volumes:
    - postgres-data:/var/lib/postgresql/data
  networks:
    - app-network

# Docker Network
networks:
  app-network:
    driver: bridge

# Docker Volumes
volumes:
  postgres-data: